#three-tier-web-app meta

---
dependencies:
  - role: aci-model

  - role: application_profile
    #( tenant_name and ap_name passed through from top-level playbook )
    # tenant_name: "{{ tenant_name }}"
    # ap_name: "{{ ap_name }}"
    description: test application from ansible

  - role: contract
    # tenant_name: "{{ tenant_name }}"
    contract_name: rmi
    filter_name_list:
      - rmi

  - role: contract
    # tenant_name: "{{ tenant_name }}"
    contract_name: sql
    filter_name_list:
      - sql

  - role: epg
    # tenant_name: "{{ tenant_name }}"
    # ap_name: "{{ ap_name }}"
    epg_name: db
    description: db epg from ansible
    bd_name: ACILab_BD1
    domain_dn_list:
      - uni/vmmp-VMware/dom-aci-vc-1
    provided_list:
      - sql



  - role: epg
    # tenant_name: "{{ tenant_name }}"
    # ap_name: "{{ ap_name }}"
    epg_name: app
    description: app epg from ansible
    bd_name: ACILab_BD1
    domain_dn_list:
      - uni/vmmp-VMware/dom-aci-vc-1
    provided_list:
      - rmi
    consumed_list:
      - sql

  - role: filter
    # tenant_name: "{{ tenant_name }}"
    filter_name: rmi
    filter_entries: 
      - name: tcp8080
        ether_type: ip
        proto: tcp
        dest_from_port: "8080"
        dest_to_port: "8080"

  - role: filter
    # tenant_name: "{{ tenant_name }}"
    filter_name: sql
    filter_entries: 
      - name: tcp1366
        ether_type: ip
        proto: tcp
        dest_from_port: "1366"
        dest_to_port: "1366"
